### ISSUE TITLE
Can't distinguish properly between rooms. 

### ISSUE THREAD

**Issue by ryansturgill** [gazaskygeeks/room-booker#63]
@saralk @ronanyeah I don't understand the differences between the four conference rooms especially when there are no photos of the rooms still (see screenshot). What's the difference between GSG Conference Room and GSG Staff Room? GSG Meeting Room I think is the main coworking space area, but the name as it is currently is not descriptive enough. 

![screenshot 2017-05-31 11 01 29](https://cloud.githubusercontent.com/assets/25309491/26621854/eaaab19e-45f0-11e7-931b-1a9ca78769cb.png)

**Comment by saralk** [comment]
I think what we can do here is put the photos up (i'll take some photos), have some more descriptive names, and put signs up on the doors with the room names.
